/**
 * Level 8 — Sub-agent Types Tests
 *
 * Tests for type validation, config defaults, ID format,
 * and trace metadata construction.
 */

import { describe, it, expect } from "vitest";
import {
    isSpawnableAgentType,
    buildSubAgentTraceMetadata,
    MAX_SPAWN_DEPTH,
    DEFAULT_CONCURRENCY_LIMIT,
    DEFAULT_TIMEOUT_MS,
    DEFAULT_MAX_ITERATIONS,
} from "baseclaw-agent/src/subagent/types.js";
import type { SubAgentState } from "baseclaw-agent/src/subagent/types.js";

describe("Level 8 — Sub-agent Types", () => {
    describe("isSpawnableAgentType", () => {
        it("returns true for the 4 main agent types", () => {
            expect(isSpawnableAgentType("ideation")).toBe(true);
            expect(isSpawnableAgentType("planning")).toBe(true);
            expect(isSpawnableAgentType("execution")).toBe(true);
            expect(isSpawnableAgentType("reviewer")).toBe(true);
        });

        it("returns false for conversation agent", () => {
            expect(isSpawnableAgentType("conversation")).toBe(false);
        });

        it("returns false for invalid agent types", () => {
            expect(isSpawnableAgentType("unknown")).toBe(false);
            expect(isSpawnableAgentType("")).toBe(false);
            expect(isSpawnableAgentType("sub-ideation")).toBe(false);
        });
    });

    describe("Constants", () => {
        it("MAX_SPAWN_DEPTH is 1", () => {
            expect(MAX_SPAWN_DEPTH).toBe(1);
        });

        it("DEFAULT_CONCURRENCY_LIMIT is 5", () => {
            expect(DEFAULT_CONCURRENCY_LIMIT).toBe(5);
        });

        it("DEFAULT_TIMEOUT_MS is 10 minutes", () => {
            expect(DEFAULT_TIMEOUT_MS).toBe(600_000);
        });

        it("DEFAULT_MAX_ITERATIONS is 25", () => {
            expect(DEFAULT_MAX_ITERATIONS).toBe(25);
        });
    });

    describe("buildSubAgentTraceMetadata", () => {
        it("builds correct trace metadata from sub-agent state", () => {
            const state: SubAgentState = {
                id: "ideation-sub-abc123",
                parentAgentId: "parent-agent-1",
                agentType: "ideation",
                status: "running",
                task: "Explore brainstorming approaches",
                tenantId: "tenant-1",
                inheritedSkillIds: ["skill-1", "skill-2"],
                inheritedMCPServerIds: ["mcp-server-1"],
                ownMCPServerIds: [],
                traceId: "trace-sub-1",
                parentTraceId: "trace-parent-1",
                workingMemory: null,
                spawnedAt: new Date().toISOString(),
            };

            const metadata = buildSubAgentTraceMetadata(state);

            expect(metadata.is_sub_agent).toBe(true);
            expect(metadata.parent_agent_id).toBe("parent-agent-1");
            expect(metadata.parent_trace_id).toBe("trace-parent-1");
            expect(metadata.sub_agent_id).toBe("ideation-sub-abc123");
            expect(metadata.inherited_skills).toEqual(["skill-1", "skill-2"]);
            expect(metadata.inherited_mcp_servers).toEqual(["mcp-server-1"]);
        });

        it("handles empty inheritance arrays", () => {
            const state: SubAgentState = {
                id: "execution-sub-xyz",
                parentAgentId: "parent-2",
                agentType: "execution",
                status: "running",
                task: "Execute task",
                tenantId: "tenant-1",
                inheritedSkillIds: [],
                inheritedMCPServerIds: [],
                ownMCPServerIds: [],
                traceId: "trace-sub-2",
                parentTraceId: "trace-parent-2",
                workingMemory: null,
                spawnedAt: new Date().toISOString(),
            };

            const metadata = buildSubAgentTraceMetadata(state);

            expect(metadata.inherited_skills).toEqual([]);
            expect(metadata.inherited_mcp_servers).toEqual([]);
        });
    });

    describe("Sub-agent ID format", () => {
        it("follows the pattern {parentAgentType}-sub-{uuid}", () => {
            const idPattern = /^(ideation|planning|execution|reviewer)-sub-[a-f0-9-]{36}$/;

            // These would be generated by the lifecycle module
            expect(idPattern.test("ideation-sub-550e8400-e29b-41d4-a716-446655440000")).toBe(true);
            expect(idPattern.test("planning-sub-550e8400-e29b-41d4-a716-446655440000")).toBe(true);
            expect(idPattern.test("execution-sub-550e8400-e29b-41d4-a716-446655440000")).toBe(true);
            expect(idPattern.test("reviewer-sub-550e8400-e29b-41d4-a716-446655440000")).toBe(true);

            // Invalid patterns
            expect(idPattern.test("conversation-sub-550e8400-e29b-41d4-a716-446655440000")).toBe(false);
            expect(idPattern.test("ideation-550e8400-e29b-41d4-a716-446655440000")).toBe(false);
        });
    });
});
